### ISSUE TITLE
Failing Healthcheck CI

### ISSUE THREAD

**Issue by StijnKas** [pegasystems/pega-datascientist-tools#102]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

CI is failing for the healthcheck: https://github.com/pegasystems/pega-datascientist-tools/actions/runs/5334143808/jobs/9665541017. @yusufuyanik1, could you take a look once you're back from PTO? I didn't change anything in the source since the last test, so I suspect it may be a dependency thing (probably Polars).

### Reproducible example

```Python
ComputeError: the length of the window expression did not match that of the group
> group: ("OmniAdaptiveModel")
> group length: 1
> output: 'shape: (1,)
Series: '' [list[str]]
[
	["OmniAdaptiveModel", "OmniAdaptiveModel", … "OmniAdaptiveModel"]
]'

Error originated in expression: 'SORT col("Configuration") BY [col("PerformanceBin"), col("PredictorName")] REVERSE ORDERING [false].slice(offset=-20, length=20).list().over([col("Configuration")])'
```

### Expected behavior

Passing CI :) 

### Installed versions

<details>

```
GitHub Actions
```

</details>

**Comment by yusufuyanik1** [comment]
This is fixed with the [PR](https://github.com/pegasystems/pega-datascientist-tools/pull/99)
