### ISSUE TITLE
ADMExplained Code Run with default or No change Scenario

### ISSUE THREAD

**Issue by CPan007** [pegasystems/pega-datascientist-tools#104]
Dear Team,

I am using lateest PDSTool having version as v3.1.11.
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/1f6cb240-a31f-4bfa-960c-1f1d431becb6)

I am using the ADMExplained.ipynb  python file from Git and running in Jupyter Notebook 6.5.2 with python version 3.10.9, Anaconda 3. I am facing some issues in running the code in as-is mode with packages's default dataset

dm = datasets.CDHSample(subset=False)
model = dm.combinedData.filter(
    (pl.col("Name") == "AutoNew36Months") & (pl.col("Channel") == "SMS")
)

modelpredictors = (
    dm.combinedData.join(
        model.select(pl.col("ModelID").unique()), on="ModelID", how="inner"
    )
    .filter(pl.col("EntryType") != "Inactive")
    .with_columns(Action=pl.concat_str(["Issue", "Group"], separator="/"))
    .collect()
)

predictorbinning = modelpredictors.filter(
    pl.col("PredictorName") == "IH.SMS.Outbound.Accepted.pyHistoricalOutcomeCount"
).sort("BinIndex")

This complied and run perfectly but to see the model overview (the next of the code, as explained below) 
modelpredictors.select(
    pl.col("Action").unique(),
    pl.col("Channel").unique(),
    pl.col("Name").unique(),
    pl.col("PredictorName").unique().sort().list()
    .arr.join(", ").alias("Active Predictors"),
    (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
).to_pandas().T.set_axis(["Values"], axis=1)

we got an error as 

TypeError                                 Traceback (most recent call last)
Cell In[13], line 5
      1 modelpredictors.select(
      2     pl.col("Action").unique(),
      3     pl.col("Channel").unique(),
      4     pl.col("Name").unique(),
----> 5     pl.col("PredictorName").unique().sort().list()
      6     .arr.join(", ").alias("Active Predictors"),
      7     (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
      8 ).to_pandas().T.set_axis(["Values"], axis=1)

TypeError: 'ExprListNameSpace' object is not callable

The second question if I want to use my custom data set (I have ADMdataMart zip or json available at local file system) , how can I replace first line of the code to generate the variable "dm".

Error screesnhot is attached .
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/417e578b-daa7-4c76-b79e-981bd11319d9)

Many thanks in advance !!

**Comment by StijnKas** [comment]
Hi, please check if you're using the latest version of the notebook. Polars recently had a breaking change ('arr' was renamed to 'list', 'list()' to 'implode()') - so that would break this. It should have been fixed in this document when we released V3.1.11, but you may still be trying to run the older version of the document.

**Comment by CPan007** [comment]
Dear @StijnKas ,

Hope you have a great weekend !! 
Thanks for your update..

I have downloaded the new vesion of the code (ADMExplained.ipynb) from Git.  I was trying to run the new code with my custom ADM file , got the error at same step as in last post..

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/2d7f2593-1cf1-4764-a0c1-e532c0a710e2)


and the error part 
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/d35aec20-52e3-401c-9115-0fc1a80fb441)


Full Error Stack :- 

ValueError                                Traceback (most recent call last)
Cell In[17], line 1
----> 1 modelpredictors.select(
      2     pl.col("Action").unique(),
      3     pl.col("Channel").unique(),
      4     pl.col("Name").unique(),
      5     pl.col("PredictorName").unique().sort().implode()
      6     .list.join(", ").alias("Active Predictors"),
      7     (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
      8 ).to_pandas().T.set_axis(["Values"], axis=1)

File ~\anaconda3\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\anaconda3\lib\site-packages\pandas\core\frame.py:5184, in DataFrame.set_axis(self, labels, axis, inplace, copy)
   5137 @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "labels"])
   5138 @Appender(
   5139     """
   (...)
   5182     copy: bool | lib.NoDefault = lib.no_default,
   5183 ):
-> 5184     return super().set_axis(labels, axis=axis, inplace=inplace, copy=copy)

File ~\anaconda3\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\anaconda3\lib\site-packages\pandas\core\generic.py:808, in NDFrame.set_axis(self, labels, axis, inplace, copy)
    805     copy = True
    807 self._check_inplace_and_allows_duplicate_labels(inplace)
--> 808 return self._set_axis_nocheck(labels, axis, inplace, copy=copy)

File ~\anaconda3\lib\site-packages\pandas\core\generic.py:818, in NDFrame._set_axis_nocheck(self, labels, axis, inplace, copy)
    814 else:
    815     # With copy=False, we create a new object but don't copy the
    816     #  underlying data.
    817     obj = self.copy(deep=copy)
--> 818     setattr(obj, obj._get_axis_name(axis), labels)
    819     return obj

File ~\anaconda3\lib\site-packages\pandas\core\generic.py:5915, in NDFrame.__setattr__(self, name, value)
   5913 try:
   5914     object.__getattribute__(self, name)
-> 5915     return object.__setattr__(self, name, value)
   5916 except AttributeError:
   5917     pass

File ~\anaconda3\lib\site-packages\pandas\_libs\properties.pyx:69, in pandas._libs.properties.AxisProperty.__set__()

File ~\anaconda3\lib\site-packages\pandas\core\generic.py:823, in NDFrame._set_axis(self, axis, labels)
    821 def _set_axis(self, axis: int, labels: AnyArrayLike | list) -> None:
    822     labels = ensure_index(labels)
--> 823     self._mgr.set_axis(axis, labels)
    824     self._clear_item_cache()

File ~\anaconda3\lib\site-packages\pandas\core\internals\managers.py:230, in BaseBlockManager.set_axis(self, axis, new_labels)
    228 def set_axis(self, axis: int, new_labels: Index) -> None:
    229     # Caller is responsible for ensuring we have an Index object.
--> 230     self._validate_set_axis(axis, new_labels)
    231     self.axes[axis] = new_labels

File ~\anaconda3\lib\site-packages\pandas\core\internals\base.py:70, in DataManager._validate_set_axis(self, axis, new_labels)
     67     pass
     69 elif new_len != old_len:
---> 70     raise ValueError(
     71         f"Length mismatch: Expected axis has {old_len} elements, new "
     72         f"values have {new_len} elements"
     73     )

ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements

**Comment by yusufuyanik1** [comment]
Hi @CPan007,

Thanks for reaching out.

Some parts of this example notebook is specific to our Sample CDH Data. We are selecting a model and a predictor that exists in CDH Sample data but doesn't exist in yours. For example here:
`model = dm.combinedData.filter(
    (pl.col("Name") == "AutoNew36Months") & (pl.col("Channel") == "SMS")
)` we are choosing a model named "AutoNew36Months" in "SMS" channel.

Also here:
`predictorbinning = modelpredictors.filter(
    pl.col("PredictorName") == "IH.SMS.Outbound.Accepted.pyHistoricalOutcomeCount"
).sort("BinIndex")`
we are picking one predictor that might not exist in your data.
So the error is probably because after applying these filters you are getting an empty dataframe.

**Comment by CPan007** [comment]
Hi @yusufuyanik1 

Thanks for the update.

As you suggested , I have changed the filtering criteria as per our data in this part of the code,  model = dm.combinedData.filter(....)

Firstly , 

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/433694ee-bd3c-4af3-b4b6-0752d92f9603)


Where the Name-predictor combination Table looks like below 
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/91f1b47c-1991-4723-b013-89c5bbd47320)


Secondly,

Changing the filter based on Model name obtained from my above Name-predictor combination Table
model = dm.combinedData.filter(
    (pl.col("Name") == "HomeLoan"))

and 

predictorbinning = modelpredictors.filter(
    pl.col("PredictorName") == "IH.Mobile.Inbound.Impression.pyHistoricalOutcomeCount"
).sort("BinIndex")

where I got this "IH.Mobile.Inbound.Impression.pyHistoricalOutcomeCount" Predictor Name from my table (4th one in Name-predictor combination Table)


In both the cases , 

I am still getting the following error : 
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/25bf69d7-a8ae-422e-b74a-245b25ca6323)


please find Full Error Stack : 
ComputeError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 modelpredictors.select(
      2     pl.col("Action").unique(),
      3     pl.col("Channel").unique(),
      4     pl.col("Name").unique(),
      5     pl.col("PredictorName").unique().sort().implode()
      6     .list.join(", ").alias("Active Predictors"),
      7     (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
      8 ).to_pandas().T.set_axis(["Values"], axis=1)

File ~\anaconda3\lib\site-packages\polars\dataframe\frame.py:7161, in DataFrame.select(self, *exprs, **named_exprs)
   7059 def select(
   7060     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7061 ) -> DataFrame:
   7062     """
   7063     Select columns from this DataFrame.
   7064 
   (...)
   7159 
   7160     """
-> 7161     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~\anaconda3\lib\site-packages\polars\lazyframe\frame.py:1504, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1493     common_subplan_elimination = False
   1495 ldf = self._ldf.optimization_toggle(
   1496     type_coercion,
   1497     predicate_pushdown,
   (...)
   1502     streaming,
   1503 )
-> 1504 return wrap_df(ldf.collect())

ComputeError: series length 3 doesn't match the dataframe height of 9



Additionally, as you suggested to print out how each of the dataframes look before moving on to the next cell, but I can see dm object is not a Dataframe type , its returning a type of 
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/7a1aedb7-9a51-4a3f-a506-a739dc55ff73)

hence head() is also failing on dm object..

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/3b2a30ad-d2b4-4c6e-8144-585f24cd359a)

Can you additionally share how to check the data summary coming from ADM file ?

Thanks in advance for yiur help..

**Comment by CPan007** [comment]
Hi @yusufuyanik1 ,

Thanks for your suggestions..

I have checked the model,predictors table right before the cell that gets error and found if it is not empty.

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/791700bb-7f9c-4af5-9f7f-891502ab5ed2)

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/eb560456-bffd-470d-8e62-884961e8a550)

As per your suggestions , I try the code with pandas but unable to run

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/c1d328d4-7f8c-4295-8cf4-363823f6059c)

As per your advice, I removed this part: pl.col("PredictorName").unique().sort().implode() .list.join(", ").alias("Active Predictors")
But it still getting error at the same step at the same code in Model Overview steps:

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/97dabb96-9244-478e-85b3-5809d45c1b8f)

Error Full Stack : 

---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[15], line 1
----> 1 modelpredictors.select(
      2     pl.col("Action").unique(),
      3     pl.col("Channel").unique(),
      4     pl.col("Name").unique(),
      5     (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
      6 ).to_pandas().T.set_axis(["Values"], axis=1)

File ~\anaconda3\lib\site-packages\polars\dataframe\frame.py:7161, in DataFrame.select(self, *exprs, **named_exprs)
   7059 def select(
   7060     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7061 ) -> DataFrame:
   7062     """
   7063     Select columns from this DataFrame.
   7064 
   (...)
   7159 
   7160     """
-> 7161     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~\anaconda3\lib\site-packages\polars\lazyframe\frame.py:1504, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1493     common_subplan_elimination = False
   1495 ldf = self._ldf.optimization_toggle(
   1496     type_coercion,
   1497     predicate_pushdown,
   (...)
   1502     streaming,
   1503 )
-> 1504 return wrap_df(ldf.collect())

ComputeError: series length 3 doesn't match the dataframe height of 4


Additionally I was trying to check the subsequent codes in the same ADMExplain.ipynb file in "as-is" format , but its failing  

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/39dadc50-0fee-427c-a41a-e4bc0fc46254)


Thanks in advance for your help.

**Comment by yusufuyanik1** [comment]
Hi,

1. dm.modelData.collect.to_pandas(): 
I accidentaly skipped the paranthesis after collect function. Please run this:
`dm.modelData.collect().to_pandas()`

2. Can you replace the failing cell:
`modelpredictors.select(
    pl.col("Action").unique(),
    pl.col("Channel").unique(),
    pl.col("Name").unique(),
    pl.col("PredictorName").unique().sort().implode()
    .list.join(", ").alias("Active Predictors"),
    (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
).to_pandas().T.set_axis(["Values"], axis=1)`

with this code:
`modelpredictors.select(
    pl.col("Action").unique().sort().implode().list.join(", "),
    pl.col("Channel").unique().sort().implode().list.join(", "),
    pl.col("Name").unique().sort().implode().list.join(", "),
    pl.col("PredictorName")
    .unique()
    .sort()
    .implode()
    .list.join(", ")
    .alias("Active Predictors"),
    (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
).to_pandas().T.set_axis(["Values"], axis=1)` 

3. In the last point I see that you are getting a NoData error. When you say "as-is" format, do you keep everything untouched including the default dataset or are you running with your own dataset? Again if you are running with your own dataset make sure that in the code when we filter for Action and PredictorName, they exist in your own data. Can't see the full error log but looks like predictorbinning dataframe was empty. 

Thanks

**Comment by operdeck** [comment]
Anything new on this? Or can we close the issue?

**Comment by CPan007** [comment]
Hi @yusufuyanik1 ,

As we are facing multiple challenges posted in last comments above ,I have checked and installed latest PDSTool version v12 which released last week by your team. Additionally to confirm my other Infra need is fully updated and not a blocker, I have meanwhile updated to Windows 11 with Python 3.10.9 and Jupyter Notebook 6.5.2

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/ee8a6aa3-57e8-42a2-a4b9-c12cb8d6195d)

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/96b755c0-00cc-4ce3-a8fb-83b2b5443a69)


![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/09a014ec-2c4c-47ed-b35c-dd194fd58e12)



Now for Point 3 of last question, I am was trying to run both , first with OOTB default dataset and then with my custom dataset(with appropriate predictor name change in the code) having final objective is to run my own custom dataset imported from my CDH ADM v8.6.

1) With packaged default dataset and OOTB code, unable to run third step, Model Overview , of ADMExplained.ipynb file .

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/e692cc2f-2729-4afe-b44d-1ab2889bbe44)

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/9c5ba975-f057-4c4a-a9d5-aac3675bbd7e)

Full error stack : 
TypeError                                 Traceback (most recent call last)
Cell In[11], line 5
      1 modelpredictors.select(
      2     pl.col("Action").unique(),
      3     pl.col("Channel").unique(),
      4     pl.col("Name").unique(),
----> 5     pl.col("PredictorName").unique().sort().list()
      6     .arr.join(", ").alias("Active Predictors"),
      7     (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
      8 ).to_pandas().T.set_axis(["Values"], axis=1)

TypeError: 'ExprListNameSpace' object is not callable



2) Moving ahead with next program, graph_gallery.ipynb file , try to run in as-is form with packaged default dataset , got the error  

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/7f5a86e1-57ca-4c63-8221-2433fd1fee16)

Full stack : 

ComputeError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 data.plotModelsByPositives()

File ~\AppData\Roaming\Python\Python310\site-packages\pdstools\plots\plot_base.py:1271, in Plots.plotModelsByPositives(self, by, query, facets, **kwargs)
   1267 required_columns = {by, "Positives", "ModelID"}
   1268 df, facets = self._subset_data(
   1269     table, required_columns, query, facets=facets, last=last
   1270 )
-> 1271 df = self.models_by_positives_df(df, by=by).collect()
   1272 if kwargs.pop("return_df", False):
   1273     return df

File ~\AppData\Roaming\Python\Python310\site-packages\pdstools\adm\ADMDatamart.py:1139, in ADMDatamart.models_by_positives_df(self, df, by, allow_collect)
   1123     return (
   1124         result.select(
   1125             [
   (...)
   1132         .to_series()
   1133     )
   1135 modelsByPositives = df.select([by, "Positives", "ModelID"]).collect()
   1136 return (
   1137     modelsByPositives.hstack(
   1138         [
-> 1139             orderedCut(
   1140                 modelsByPositives["Positives"],
   1141             )
   1142         ]
   1143     )
   1144     .lazy()
   1145     .groupby([by, "PositivesBin"])
   1146     .agg([pl.min("Positives"), pl.n_unique("ModelID").alias("ModelCount")])
   1147     .with_columns(
   1148         (pl.col("ModelCount") / (pl.sum("ModelCount").over(by))).alias(
   1149             "cumModels"
   1150         )
   1151     )
   1152     .sort("PositivesBin")
   1153 )

File ~\AppData\Roaming\Python\Python310\site-packages\pdstools\adm\ADMDatamart.py:1119, in ADMDatamart.models_by_positives_df.<locals>.orderedCut(s, label, bins)
   1115 def orderedCut(
   1116     s, label="PositivesBin", bins=list(range(0, 210, 10))
   1117 ) -> pl.Series:
   1118     _arg_sort = pl.Series(name="_sort", values=s.arg_sort())
-> 1119     result = s.cut(
   1120         bins=[bins + [float("inf")]][0], category_label="PositivesBin"
   1121     )
   1123     return (
   1124         result.select(
   1125             [
   (...)
   1132         .to_series()
   1133     )

File ~\AppData\Roaming\Python\Python310\site-packages\polars\series\series.py:1717, in Series.cut(self, bins, labels, break_point_label, category_label, series, left_closed, include_breaks)
   1705 if not series:
   1706     # "Old style" always includes breaks
   1707     return (
   1708         self.to_frame()
   1709         .with_columns(
   (...)
   1713         .rename({"brk": break_point_label, n + "_bin": category_label})
   1714     )
   1715 res = (
   1716     self.to_frame()
-> 1717     .select(F.col(n).cut(bins, labels, left_closed, include_breaks))
   1718     .to_series()
   1719 )
   1720 if include_breaks:
   1721     return res.struct.rename_fields([break_point_label, category_label])

File ~\AppData\Roaming\Python\Python310\site-packages\polars\dataframe\frame.py:7183, in DataFrame.select(self, *exprs, **named_exprs)
   7081 def select(
   7082     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7083 ) -> DataFrame:
   7084     """
   7085     Select columns from this DataFrame.
   7086 
   (...)
   7181 
   7182     """
-> 7183     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~\AppData\Roaming\Python\Python310\site-packages\polars\lazyframe\frame.py:1531, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1520     common_subplan_elimination = False
   1522 ldf = self._ldf.optimization_toggle(
   1523     type_coercion,
   1524     predicate_pushdown,
   (...)
   1529     streaming,
   1530 )
-> 1531 return wrap_df(ldf.collect())

ComputeError: Don't include inf in breaks



3) With my custom dataset(same ADM dataset which was explained till date in this post), for ADMExplained file , got an error with while importing and combining the data 
![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/6d568c0d-a849-4a4b-a626-0097a889eace)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[41], line 7
      2 dm  =  ADMDatamart("C:/data",
      3                    model_filename = "Data-Decision-ADM-ModelSnapshot_Banking/data.json",
      4                    predictor_filename = "Data-Decision-ADM-PredictorBinningSnapshot_Banking/data.json")
      5 #dm = datasets.CDHSample(subset=False)
----> 7 model = dm.combinedData.filter(
      8     (pl.col("Name") == "HomeLoan"))
     10 modelpredictors = (
     11     dm.combinedData.join(
     12         model.select(pl.col("ModelID").unique()), on="ModelID", how="inner"
   (...)
     17     .collect()
     18 )
     20 predictorbinning = modelpredictors.filter(
     21     pl.col("PredictorName") == "IH.Mobile.Inbound.Impression.pyHistoricalOutcomeCount"
     22 ).sort("BinIndex")

AttributeError: 'ADMDatamart' object has no attribute 'combinedData'


I was exploring so many directions in PDSTool OOTB features, hence sharing multiple observations at one shot..

Many thanks in advance..

**Comment by yusufuyanik1** [comment]
Hi @CPan007,

Thanks again for exploring pdstools and reporting your issues.

1. We will release a slightly modified ADMExplained notebook in which the bugs will be addressed and it will be easier to run on a custom dataset. Meanwhile, you can check a newer version of the article [here](https://github.com/pegasystems/pega-datascientist-tools/blob/master/examples/articles/ADMExplained.ipynb). This shouldn't break with default dataset and OOTB code. 

2. I see the same error on my system when I use polars with the latest(0.18.7) version which you also have. Polars rapidly updates their library and sometimes we get breaking changes without a lot warning prior to the change. I will investigate what exactly caused that but meanwhile you can downgrade your polars version to 0.18.0.  The default code and data should work once downgraded. To downgrade you can run `!pip install polars==0.18.0` on your jupyter notebook and then restart the notebook to make sure that change is applied.

3. This error is a bit strange. Can you please run these seperatly to check whether our adm class reads model data and predictor data correctly `dm.modelData.collect()` and `dm.predictorData.collect()` ? 

Thanks.

**Comment by CPan007** [comment]
Thanks @yusufuyanik1 for the quick reply.

As requested , for Point # 3, I got same :) 

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/59d0c7b8-abfe-4e7e-b380-a3a2abe9812b)

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/19f13d41-6f5e-47c0-90d8-97e7b00f80f2)


For # 1, 2 kindly inform me once the new code/package is available to explore so that I can run it for my custom dataset..Meanwhile I will also try for OOTB packaged dataset.

Have a nice week!!

**Comment by yusufuyanik1** [comment]
Hi @CPan007,

We have published a new version of pdstools. You can upgrade your library by running:
`pip install --upgrade pdstools` on your working environment.

1. Errors in ADMExplained have been addresses. To run with your own data you can change the first 3 variables to adjust to your data: 
`model_name = "AutoNew84Months"
predictor_name = "Customer.NetWealth"
channel= "Web"
`
and the "dm" object with your own data in the 2nd cell
You can find the article here: https://pegasystems.github.io/pega-datascientist-tools/Python/articles/ADMExplained.html

2. Error in graph gallery has been fixed. Here is the link to the article: https://pegasystems.github.io/pega-datascientist-tools/Python/articles/graph_gallery.html
3. I am not sure what is causing this error. Can you please double check the paths you provide to the ADMDatamart class. If you are still not able to collect() your dm.modelData, can you check if you can read your modelData.json with polars or pandas?
With polars you can read modelData like this:
`pl.read_ndjson(path/to/data)`

Thank you

**Comment by CPan007** [comment]
Hi Team, 

Many thanks for looking/replicating my observations and then publishing new version for the PDSTool..


For # 1, 

I have upgraded PDS version to the new released one. keeping other parts as is and running on OOTB dataset bundled within PDSTool package, I have modified the code as per your suggestion,   :
model_name = "AutoNew84Months" predictor_name = "Customer.NetWealth" channel= "Web" 



![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/93bde182-b8d8-4932-9531-ef32b7a7aad5)


![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/64c83600-d558-4c7e-a822-b356ed688ed6)

Now the dm object is populated perfectly :

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/9a9ab409-e2ee-4cc9-84b3-c4a729ebd96b)

However, when I am trying to run the OOTB code for the next part i.e "Predictor binning" of the ADMExplained.ipynb , I got the following error..

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/2451981a-dadd-435c-bfba-19024be9c776)

Full Stack of Error: 

ColumnNotFoundError                       Traceback (most recent call last)
Cell In[17], line 6
      3 sumPositives = pl.sum("BinPositives")
      4 sumNegatives = pl.sum("BinNegatives")
----> 6 predictorbinning.select(
      7     pl.col("BinSymbol").alias("Range/Symbol"),
      8     ((BinPositives + BinNegatives) / (sumPositives + sumNegatives))
      9     .round(3)
     10     .alias("Responses (%)"),
     11     BinPositives.alias("Positives"),
     12     (BinPositives / sumPositives).round(3).alias("Positives (%)"),
     13     BinNegatives.alias("Negatives"),
     14     (BinNegatives / sumNegatives).round(3).alias("Negatives (%)"),
     15     (BinPositives / (BinPositives + BinNegatives)).round(4).alias("Propensity (%)"),
     16     pl.col("ZRatio"),
     17     pl.col("Lift"),
     18 ).to_pandas()

File ~\anaconda3\lib\site-packages\polars\dataframe\frame.py:7161, in DataFrame.select(self, *exprs, **named_exprs)
   7059 def select(
   7060     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7061 ) -> DataFrame:
   7062     """
   7063     Select columns from this DataFrame.
   7064 
   (...)
   7159 
   7160     """
-> 7161     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~\anaconda3\lib\site-packages\polars\lazyframe\frame.py:1504, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1493     common_subplan_elimination = False
   1495 ldf = self._ldf.optimization_toggle(
   1496     type_coercion,
   1497     predicate_pushdown,
   (...)
   1502     streaming,
   1503 )
-> 1504 return wrap_df(ldf.collect())

ColumnNotFoundError: ZRatio

Error originated just after this operation:
DF ["Direction", "SnapshotTime", "Performance", "ModelID"]; PROJECT */32 COLUMNS; SELECTION: "None"




For # 3 - for our custom dataset, with the new version of the Tool, data is getting imported.


![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/fe048605-7a7c-4e52-8820-753c1d540fc1)

Snap of the data :

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/3173714b-3233-42fa-b98b-d7c1f14f89aa)


![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/aa40df18-261e-4b49-8c91-4b61e4ec3c05)


![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/13c9d89f-255a-4962-944f-6cac3aff24a5)


![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/180c33e3-99a8-4805-88d1-5e61f8c43524)


But , immediately in the next part , when I run the OOTB for Model Overview code, kindly find the observations

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/137057930/a4850a4e-e026-4d59-83e2-f4412c7a7563)

Full Stack of Error: 

ComputeError                              Traceback (most recent call last)
Cell In[16], line 1
----> 1 modelpredictors.select(
      2     pl.col("Action").unique(),
      3     pl.col("Channel").unique(),
      4     pl.col("Name").unique(),
      5     pl.col("PredictorName").unique().sort().implode()
      6     .list.join(", ").alias("Active Predictors"),
      7     (pl.col("Performance").unique() * 100).alias("Model Performance (AUC)"),
      8 ).to_pandas().T.set_axis(["Values"], axis=1)

File ~\AppData\Roaming\Python\Python310\site-packages\polars\dataframe\frame.py:7183, in DataFrame.select(self, *exprs, **named_exprs)
   7081 def select(
   7082     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   7083 ) -> DataFrame:
   7084     """
   7085     Select columns from this DataFrame.
   7086 
   (...)
   7181 
   7182     """
-> 7183     return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)

File ~\AppData\Roaming\Python\Python310\site-packages\polars\lazyframe\frame.py:1531, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1520     common_subplan_elimination = False
   1522 ldf = self._ldf.optimization_toggle(
   1523     type_coercion,
   1524     predicate_pushdown,
   (...)
   1529     streaming,
   1530 )
-> 1531 return wrap_df(ldf.collect())

ComputeError: series length 3 doesn't match the dataframe height of 4


Thanks again for the continuous communication and help.

**Comment by yusufuyanik1** [comment]
Hi @CPan007,

The code in the notebook file is also updated. You can find the new code here: https://github.com/pegasystems/pega-datascientist-tools/blob/master/examples/articles/ADMExplained.ipynb

Thanks

**Comment by StijnKas** [comment]
Hi @CPan007, is this still an open issue for you? If not, I'd like to close it.
