### ISSUE TITLE
HealthCheck calculation bug

### ISSUE THREAD

**Issue by yusufuyanik1** [pegasystems/pega-datascientist-tools#114]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pdstools.

### Issue description

https://github.com/pegasystems/pega-datascientist-tools/blob/master/examples/datamart/healthcheck.Rmd#L224

In the calculation above which generates a channel overview some metrics are incorrect.

### Reproducible example

```R
.
```

### Expected behavior
Responses, Positives and Base rate metrics should be sum aggregations instead of max.

**Comment by operdeck** [comment]
I've addressed this I believe with a recent PR
