### ISSUE TITLE
findShortestPath blocked by heavy rain

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#116]
![IMG-20230808-WA0000.jpg](https://github.com/pegasystems/pega-datascientist-tools/assets/4807080/60e2b565-c97b-48bb-9af4-0cd82211a2c5)

![Screenshot_20230806-210029.png](https://github.com/pegasystems/pega-datascientist-tools/assets/4807080/80503397-430f-4214-8af5-68b2b472cac6)

But all good here high up in a mountain cottage :) cheers

**Comment by operdeck** [comment]
😉

**Comment by operdeck** [comment]
All roads are now blocked but no need for escalation yet. We expect that
time and gravity will solve it while we stay high up in the mountains for a
few more days. We're still good on resources 🙂.

Op wo 9 aug. 2023 15:17 schreef Stijn Kas ***@***.***>:

**Comment by operdeck** [comment]
The priority of this issue can be lowered. We found a walk-around, so although the root cause is not resolved (roads down the mountain still closed) we found a hike into Rondane and will stay there for a while.![IMG_20230812_211359193_HDR.jpg](https://github.com/pegasystems/pega-datascientist-tools/assets/4807080/4acb04ca-2ec8-4122-bbed-ae5a4f252cd7)

**Comment by StijnKas** [comment]
Glad to see the issue closed @operdeck - any reason to doubt the 'returning home' SLA deadline?

**Comment by operdeck** [comment]
Haha no we will make the deadline
