### ISSUE TITLE
Include datamart based sample generation

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#118]
### Is your feature request related to a problem?

We have some tools/scripts developed in-house to generate a dataset from an ADM datamart that mimics the (univariate) distribution. Such scripts could be of use to a broader audience. Such a dataset might be useful to port ADM statistics from one system to another if this is not possible in any direct way.

### Describe the solution you'd like

Take the existing tool (originally in R but got ported to Python) and make part of PDS tools - including an example NB, Wiki content etc

### Describe alternatives you've considered

NA

**Comment by operdeck** [comment]
https://git.pega.io/projects/DS/repos/data-generation/browse

**Comment by StijnKas** [comment]
Not needed as functionality in pdstools, closing.
