### ISSUE TITLE
Include cross-channel group level ADM binning plots in Health Check

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#119]
### Is your feature request related to a problem?

We can create model reports for individual ADM model instances. They provide useful insights from the predictor binning:

![image](https://github.com/pegasystems/pega-datascientist-tools/assets/4807080/4c86b389-45e4-42a0-b117-bd32b28ad12a)

However with many model instances (100's or 1000's) it is difficult to generalize these insights manually.

We would like to have a facility that rolls up individual model predictor binning to an aggregate form that can be part of the standard Health Check. The aggregation could be up to Groups by default. It could also be cross-channel, when we normalize the click through rates. I believe this might be very useful to business. This could give insights like "who generally accepts cards offers". We can also do a per-channel aggregation, giving insights into who prefers which channel.

### Describe the solution you'd like

Binnings for multiple instances can be merged algorithmically. When the types are different (exceptionally) we bail out. String labels can be spit, for numerics even easier. We can initially create new binnings with the highest granularity then roll them up in a post processing step - combining bins in perhaps a similar manner as the standard grouping algorithm of ADM/PAD do this.

If we shoot for just the propensity lift plots (not absolute lift), we can nicely aggregate over channels by normalizing propensity relative to the channel base propensity.

### Describe alternatives you've considered

N/A

### Additional context

We already have some proprietary (Python) code to roll up bins efficiently.

**Comment by operdeck** [comment]
Working on it...

**Comment by operdeck** [comment]
Added a supporting ADMBinningInsights class and an explanatory notebook

**Comment by StijnKas** [comment]
We want to add this to the pdstools app still, but the class & article are there, so closing it.
