### ISSUE TITLE
Entropy: How Much optionality do we present?

### ISSUE THREAD

**Issue by yusufuyanik1** [pegasystems/pega-datascientist-tools#120]
### Is your feature request related to a problem?

We know that optionality matters for 1:1 experience. We can see how many actions we have in the action catalog and have an idea about how often we present them from the sizes of bubble. But there is no direct metric for optionality. Perhaps having 1 number that we can highlight if it is very low, it could be a good alarm.

### Describe the solution you'd like

The idea emerged from the plot below which shows that a customer keeps showing 5 actions over 80% of the time. Instead of showing a graph we can create a standard metric and interpret it cross-customers.
<img width="787" alt="Screenshot 2023-09-20 at 14 59 31" src="https://github.com/pegasystems/pega-datascientist-tools/assets/54443450/872d37b8-efcf-42ad-8733-6f6e95af9a51">

### Describe alternatives you've considered

We can think about how to generalize the metric

**Comment by operdeck** [comment]
0 = everyone getting the same thing, no entropy
100 = everyone getting something unique

Everyone unique seems unlikely but if there is a top 3 with just 200
actions there are enough combinations to cover a very large customer base.

Op wo 20 sep. 2023 15:11 schreef yusufuyanik1 ***@***.***>:

**Comment by yusufuyanik1** [comment]
We created a function in Decision Analyzer to calculate area under the curve which represents entropy
