### ISSUE TITLE
Health Check (Python) alignment

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#136]
### Is your feature request related to a problem?

Completely align Python version of health check with the R version - except where there are improvements already (e.g. tree map of missing values)

### Describe the solution you'd like

All numbers and text aligned with R version, robust against all versions of the DM we have, use nice Quarto features where applicable (like in the offline model reports). Rework plotting code to the pdstools library where appropriate.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by StijnKas** [comment]
At this point I think the Python health check is more feature-complete than the R version, so closing this (fyi @operdeck)
