### ISSUE TITLE
Performance plot has odd title

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#167]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

_plotPredictorPerformance_ puts "Predictor PerformanceBin <configuration>" in the title. I think I know why but it is not helping end users. Lets drop the Predictor PerformanceBin part and just keep the configuration name.

The plot code is so layered that it's not trivial for me to make the change myself.

<img width="821" alt="Untitled" src="https://github.com/pegasystems/pega-datascientist-tools/assets/4807080/303b6f2c-707d-4984-89bb-f4ea2719c209">

### Reproducible example

```Python
blah
```

### Expected behavior

simple title

### Installed versions

---Version info---
pdstools: 3.2.5
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]

---Dependencies---
plotly: 5.16.1
requests: 2.25.1
pydot: 1.4.2
polars: 0.19.5
pyarrow: 8.0.0
tqdm: 4.59.0
pyyaml: <not installed>
aioboto3: 11.2.0

---Streamlit app dependencies---
streamlit: 1.20.0
quarto: 0.1.0
papermill: 2.4.0
itables: 1.5.2
pandas: 1.5.3
jinja2: 3.1.2
xlsxwriter: 3.1.1

**Comment by operdeck** [comment]
Same for this of course: plotPredictorCategoryPerformance

**Comment by yusufuyanik1** [comment]
Resolved with: 
https://github.com/pegasystems/pega-datascientist-tools/commit/bdc8422a4cbc12ef2e079935f84ce67d1c64c222
