### ISSUE TITLE
Python model reports cosmetics

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#175]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

1. Classifier should show the "active range" similar to the R version. This helps identifiying problems with individual models. The cum gains and lift chart should also be using this active range.
2. X-ticks of classifier should probably be tilted (like the individual binnngs) or just replaced with index (table is available anyways) and layout should autofit - currently cuts off sometimes.
3. Predictor categories should be propagated and used to highlight/color the various predictor overviews
4. Predictor Overview should add column with # of responses, as this sometimes varies and when it does, thats interesting info
5. Predictor Overview should make use of predictor groups and group them, similar to R version
6. Predictor Binning plots should do auto-layout of y-axis, sometimes cut off or overlapping

### Reproducible example

```Python
n/a
```

### Expected behavior

at par or better than R version of model reports, we currently still have to pull those for additional info

### Installed versions

n/a

**Comment by StijnKas** [comment]
I think the Python model reports are now more feature-complete than the R version, so I think we can safely close this issue.

Fyi @yusufuyanik1, it may be worth checking if any of these mentioned issues still persist, but I get the feeling that most of them are covered by now.
