### ISSUE TITLE
Install fails due to "pROC" dependency

### ISSUE THREAD

**Issue by AntonTal** [pegasystems/pega-datascientist-tools#186]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pdstools.

### Issue description

Installing pdstools with "build_vignettes=TRUE" requires the "pROC" library to be preinstalled, so when running 
"install_github("pegasystems/pega-datascientist-tools/r", build_vignettes=TRUE)" on a clean system fails the instalment. Seemingly the pROC is used in "adm-explained" notebook. See the error log:
<img width="608" alt="Screenshot 2024-01-11 at 09 48 28" src="https://github.com/pegasystems/pega-datascientist-tools/assets/26297353/e3462871-bce7-4644-a613-179d02d33bbc">

### Reproducible example

```R
Run "install_github("pegasystems/pega-datascientist-tools/r", build_vignettes=TRUE)" without pROC library pre-installed.
```

### Expected behavior

"install_github("pegasystems/pega-datascientist-tools/r", build_vignettes=TRUE)" should run without failure

**Comment by operdeck** [comment]
Hey Anton, thanks, I'll move pROC from suggested to required imports in the R library.

BTW note that the python version is more actively being maintained these days than the R one.
