### ISSUE TITLE
Check for / validate optional dependencies in the Streamlit app

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#200]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

Customer managed to install the health check app on Linux but with some additional tweaks.

See Anton for more info

Hi Anton,
I managed to reproduce the Health Check report
Notice we have a dev server with Red Hat Enterprise Linux Server (RHEL) release 7.9 (Maipo) as OS.  I installed Pandoc (version 3.1.1), as instructed, and installed the Quarto tarball version 1.3.450 linux-rhel7-amd64. As a sidenote: tarball installation is bypassing our security layer that scans for vulnerabilities in packages that are used, so it is somewhat frowned upon. I had to downgrade Quartro because the current version only supports RHEL8. The most recent version looks for GLIBC_2.18 which could not be found on our OS. Lastly, I had to create a symlink to make the Quarto CLI available to pdstools (so that it was on PATH).
Missing pieces
I noticed that two dependencies were missing from pdstools to create the report, specifically:
- papermill (2.5.0)
- itables (1.7.1)
After installing these, I encountered no problems in using Streamlit to render the html.
Thanks for the instructions 😉

### Reproducible example

```Python
n/a
```

### Expected behavior

n/a

### Installed versions

n/a

**Comment by operdeck** [comment]
Comment @yusufuyanik1 : 

As per the missing requirements, I believe they used the ‘pip install pdstools’ command but it doesn’t download the “optional” app dependencies. To keep the download process light for the people who are only interested in the utility functions in pdstools, not the app, we positioned app dependencies as optional. One can use the command below to install pdstools along with the app dependencies.

pip install --upgrade pdstools[app]

**Comment by StijnKas** [comment]
@yusufuyanik1  would it make sense to give a big red warning in the streamlit app when these optional dependencies aren't installed, telling the user to install as `pip install pdstools[app]`?

**Comment by StijnKas** [comment]
@yusufuyanik1, maybe we should add the dependency warning to the streamlit app as part of https://github.com/pegasystems/pega-datascientist-tools/pull/250? I don't think this is a real issue, but helping the user point out why things aren't working is always a good thing.

**Comment by StijnKas** [comment]
@yusufuyanik1 - has the dependency warning been added to the streamlit app? If so, let's close this issue. If not, could you include it as part of #260 ?
