### ISSUE TITLE
plotPredictorPerformance fails for AGB

### ISSUE THREAD

**Issue by yusufuyanik1** [pegasystems/pega-datascientist-tools#215]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

When I try to generate HealthCheck with a datamart that has only AGB configuration, plotPredictorPerformance function fails.

### Reproducible example

```Python
from pdstools import ADMDatamart
import polars as pl

dm = ADMDatamart(
        path="." ,
        model_filename="",
        predictor_filename="",
        extract_keys=True,
        include_cols="pyFeatureImportance",
        query=pl.col("Configuration") == "AGB_Configuration"
    ).fillMissing()

dm.generateReport()

"IndexError: list index out of range"
```

### Expected behavior

HealthCheck should be succesfully generated

### Installed versions

---Version info---
pdstools: 3.4.3
Platform: macOS-14.4.1-arm64-arm-64bit
Python: 3.12.3 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 11:44:52) [Clang 14.0.6 ]

---Dependencies---
plotly: 5.22.0
requests: 2.31.0
pydot: 2.0.0
polars: 0.20.25
pyarrow: 16.0.0
tqdm: 4.66.4
pyyaml: <not installed>
aioboto3: 12.4.0

---Streamlit app dependencies---
streamlit: 1.34.0
quarto: 0.1.0
papermill: 2.6.0
itables: 2.0.1
pandas: 2.2.2
jinja2: 3.1.4
xlsxwriter: 3.2.0

**Comment by StijnKas** [comment]
Have you found a root cause for this @yusufuyanik1 ? What function causes this?

**Comment by StijnKas** [comment]
@yusufuyanik1 - any updates on this? If you could, would be great if we could include this as part of #260
