### ISSUE TITLE
Show Only Active Predictors Button doesn't work in HealthCheck

### ISSUE THREAD

**Issue by yusufuyanik1** [pegasystems/pega-datascientist-tools#244]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

Show Only Active Predictors Button doesn't work in HealthCheck

### Reproducible example

```Python
.
```

### Expected behavior

Show only_active button HC used to hide inactive ones but now it doesn't

### Installed versions

---Version info---
pdstools: 3.4.4
Platform: macOS-14.5-arm64-arm-64bit
Python: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ]

---Dependencies---
plotly: 5.18.0
requests: 2.32.3
pydot: 1.4.2
polars: 0.20.31
pyarrow: 11.0.0
tqdm: 4.66.1
pyyaml: <not installed>
aioboto3: 11.0.1

---Streamlit app dependencies---
streamlit: 1.35.0
quarto: 0.1.0
papermill: 2.4.0
itables: 1.5.1
pandas: 2.1.4
jinja2: 3.1.4
xlsxwriter: 3.1.9

**Comment by StijnKas** [comment]
Is this a health check core functionality or the streamlit app? Let's do some basic RCA on this

**Comment by yusufuyanik1** [comment]
This appears to be fixed as of last version.
