### ISSUE TITLE
plotPredictorCategoryPerformance with multiple facets returns a configuration rather than a plot

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#249]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

Given a dm with model and predictor data, the following all work fine, returning the expected plots

```
dm.plotPredictorCategoryPerformance(facets=["Issue"])
dm.plotPredictorCategoryPerformance(facets=["Channel"])
dm.plotPredictorCategoryPerformance()
```

but when I combine both

`dm.plotPredictorCategoryPerformance(facets=["Issue", "Channel"])
`
I get a JSON dump of a plotly Figure configuration

```
[Figure({
     'data': [{'alignmentgroup': 'True',
               'hovertemplate': ('Legend=Customer<br>Issue=NA<br' ... 'orCategory=%{y}<extra></extra>'),
               'legendgroup': 'Customer',
               'marker': {'color': '#001F5F'},
               'name': 'Customer',
               'notched': False,
               'offsetgroup': 'Customer',
(etc)

```

<img width="803" alt="image" src="https://github.com/user-attachments/assets/7c64bbcf-e18c-4092-99b3-37ae2dc7c328">

### Reproducible example

```Python
from pdstools import ADMDatamart, datasets
dm = datasets.CDHSample()
dm.plotPredictorCategoryPerformance(facets=["Issue", "Channel"])
```

### Expected behavior

Expected a 2-d facetted plot

### Installed versions

<details>

```
---Version info---
pdstools: 3.4.4
Platform: macOS-14.5-arm64-arm-64bit
Python: 3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)]

---Dependencies---
plotly: 5.22.0
requests: 2.32.3
pydot: 2.0.0
polars: 0.20.31
pyarrow: 16.1.0
tqdm: 4.66.4
pyyaml: <not installed>
aioboto3: 13.0.1

---Streamlit app dependencies---
streamlit: <not installed>
quarto: <not installed>
papermill: 2.6.0
itables: <not installed>
pandas: 2.2.2
jinja2: 3.1.4
xlsxwriter: 3.2.0```

</details>

**Comment by StijnKas** [comment]
It's not actually a json @operdeck - it is a list of plotly objects. If you loop through them and call `show()` on them, they will appear.

It's probably not an optimal implementation, but I don't really know how else we should solve this: having it all as one big plotly plot probably doesn't improve things either.

**Comment by operdeck** [comment]
Ah in that case lets close this

Op wo 24 jul 2024 om 11:07 schreef Stijn Kas ***@***.***>
