### ISSUE TITLE
Color assignments in Health Check are inconsistent

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#256]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

The various plots in the Health Check and Model Report have inconsistent assignments of values to colors. This is confusing - especially when copy/pasting the plots together into documents.

![image](https://github.com/user-attachments/assets/b450d7b6-ca6e-43e1-bd1d-ecda7338d8ba)

![image](https://github.com/user-attachments/assets/bc78e93b-101a-4856-94e1-c888ed03dc57)

### Reproducible example

```Python
See almost any of the generated HC reports
```

### Expected behavior

The mapping of the various discrete axis should be consistent within one quarto notebook - not across different notebooks

We don't need to try to be very generic. Most plots in the Health Check with a discrete axis only use **Channel/Direction**. In a few places it is only Channel but arguably those should be using Channel/Direction instead.
 
For HC with predictor data we also have Predictor Category as a discrete option, as well as (in one place) EntryType (deserves a better name).

Plotly funcs often have a color_discrete_map argument that we should probably pass on as a dictionary from the ADMDatamart object - or something along those lines. We probably also want to fix the order of the categories with category_orders.

### Installed versions

<details>

```
Replace this line with the output of pdstools.show_versions(), leave the backticks in place
```

</details>

**Comment by StijnKas** [comment]
https://github.com/pegasystems/pega-datascientist-tools/pull/260 resolves this: we added `unique_channels`, 'unique_configurations', 'unique_channel_direction' & 'unique_predictor_categories' as cached properties to the ADMDatamart class which are the sorted categories without applying filters. So, if we consistently use these to define the color arrays, we should have consistent colors too.
