### ISSUE TITLE
Use arrow also for internal reading in readDSExport R function

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#29]
Consider arrow package for fast reading (& writing perhaps) of LDJSON files and even ordinary csv.

**Comment by StijnKas** [comment]
Implemented in Python in PR #32

**Comment by operdeck** [comment]
Using it also in ADMDatamart function in R. TODO use it also when reading the data.json from the export zips.

**Comment by operdeck** [comment]
Arrow already used by R's ADMDatamart but to be used internally also when reading the data.json file from a DS export
