### ISSUE TITLE
Add startup message

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#3]
library(googleVis) gives startup msg like this, we could do something similar

> library(googleVis)
Creating a generic function for ‘toJSON’ from package ‘jsonlite’ in package ‘googleVis’

Welcome to googleVis version 0.6.2

Please read Google's Terms of Use
before you start using the package:
https://developers.google.com/terms/

Note, the plot method of googleVis will by default use
the standard browser to display its output.

See the googleVis package vignettes for more details,
or visit http://github.com/mages/googleVis.

To suppress this message use:
suppressPackageStartupMessages(library(googleVis))

**Comment by StijnKas** [comment]
I think we can probably close this as we're not going to actively update the R tools and this is not a common practice for Python packages @operdeck
