### ISSUE TITLE
Analysis of additional datamart classes from pred studio 

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#40]
Like we have a ADMDatamart class/function we should consider doing the same to wrap the datamart tables for predictions and predictive models. Some of the plotting functions apply to both, like bubble charts etc.

See https://docs.pega.com/decision-management-reference-materials/database-tables-monitoring-models for the tables.

**Comment by StijnKas** [comment]
I don't think you mean having it be part of the ADMDatamart class, right? Would be something separate. To me that's the only way it'd make sense - they aren't ADM, so shouldn't be in *ADM* datamart

**Comment by operdeck** [comment]
I think we should create a separate notebook that recreates (most of) pred studio from the dm export that it provides.

This could also include an analysis or summary from the notifications table.

Not urgent

**Comment by operdeck** [comment]
First cut with very simple notebook on Prediction data

**Comment by operdeck** [comment]
Prediction support in Health Checks underway, isolated plots, updated Prediction notebook

**Comment by operdeck** [comment]
Done, included prediction analysis
