### ISSUE TITLE
upgrade jpmml evaluator

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#6]
Example evaluator is dated, we should move to the new codebase

see
https://github.com/jpmml/jpmml-evaluator

**Comment by StijnKas** [comment]
Still relevant @operdeck ? I think this was for a very very old java implementation of pdstools so i assume we don't need this, but it bring up a different question: Should we add pmml to the python tools?

**Comment by operdeck** [comment]
No but will keep the ADM to PMML tool alive for a bit, not planning any improvements however.
