### ISSUE TITLE
IHanalysis.py needs basic CDH feature set

### ISSUE THREAD

**Issue by dsphilli1** [pegasystems/pega-datascientist-tools#62]
CDH computes last group id, historical outcome count, last outcome time for various groups of data. bringing this into IHanalysis will let us run these analyses on data outside of CDH

**Comment by dsphilli1** [comment]
def last_group_id(df, time_window='90d', time_column='pxOutcomeTime',
                  grouping=['pySubjectID', 'pyChannel', 'pyDirection',
                            'pyOutcome'],
                  group_column = 'pyGroup'):
    """
    using the definitions from PegaDevStudio, compute the last group id on
    interaction history data


    Returns
    -------
    None.

    """

    df = (
        df.sort(time_column).
        groupby_dynamic(time_column, every=time_window, period=time_window,
                        by=grouping).agg(pl.col(group_column).tail(1))
        )
    last_group_id = df.collect()
    return(last_group_id)

**Comment by dsphilli1** [comment]
def historical_outcome_count(df, time_window='90d', time_column='pxOutcomeTime',
                  grouping=['pySubjectID', 'pyChannel', 'pyDirection'],
                  outcome_column = 'pyOutcome'):
    """
    using the definitions from Pega DevStudio, compute the historical outcome
    counts

    Returns
    -------
    None.

    """
    df = (
        df.sort(time_column).
        groupby_dynamic(time_column, every=time_window, period=time_window,
                        by=grouping)).agg(pl.col(outcome_column).value_counts())
    historical_outcome_count = df.collect()
    return(historical_outcome_count)

**Comment by StijnKas** [comment]
Working on these functions already, will add similar features sometime this week. Will reference here once done.
