### ISSUE TITLE
Special treatment for OmniAdaptiveModel in Health Check

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#76]
The NBAD framework always creates an OmniAdaptiveModel even if people are not actively using this. This is okay for the most part, most charts in the Health Check consider "configuration" as a facet.

But in the lists of models not receiving positives, negatives or neither, the distinction is more important. Perhaps these lists should be per model configuration or have some other way to include/exclude OmniAdaptiveModel.

**Comment by StijnKas** [comment]
@operdeck @yusufuyanik1 - just working through some of the older issues - is this still an open one? Should we just filter out omniadaptive for these purposes by default?

**Comment by operdeck** [comment]
No we should not filter out given the introduction of treatment action fall
back in '23

We can close this issue however


Op di 7 nov. 2023 16:11 schreef Stijn Kas ***@***.***>:

**Comment by operdeck** [comment]
Wont fix, OmniAdaptiveModel is used in fall back and should not be excluded
