### ISSUE TITLE
getS3Files to go via "meta" files

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#90]
### Is your feature request related to a problem?

Pega repository writers create ".meta" files for each file when the actual file has been transferred. To avoid picking up half-finished files we should (by default) always use these meta tag files.

They look like

```
<?xml version='1.0' encoding='UTF-8'?>
<file>
<name>interaction-4-web3705491679068813011-20230317155634_346.json</name>
<size>5468</size>
<recordCount>165</recordCount>
</file>
```

### Describe the solution you'd like

The "getS3Files" should go via those meta files instead of directly listing the files. It should filter the meta files by prefix, read them, then process the files in the "name" fields of these meta files.

### Describe alternatives you've considered

Probably an optional argument "usemeta=True", so the meta files can be bypassed

**Comment by StijnKas** [comment]
Closed by https://github.com/pegasystems/pega-datascientist-tools/commit/ce82a81d251fd324dbad1a1322d264e6ead768e9: `use_meta_files`.

The logic, if `use_meta_files` is True, is:
1. take the prefix, add a `.` in front of it (`'path/to/files'` becomes (`'path/to/.files'`)
2. fetch all files in the repo that adhere to the prefix (`'path/to/.files*'`)
3. for each file, if the file ends with `.meta`:
- take the file name, split on '/' (`['path', 'to', '.files_001.json.meta']`)
- for the last element (just the filename), strip the period and the .meta (`['path', 'to', 'files_001.json']`)
- concat back to a filepath (`'path/to/files_001.json'`)
4. Import all files in the list

If `use_meta_files` is False, the logic is as simple as:
1. Import all files starting with the prefix (`'path/to/files'` gives `['path/to/files_001.json', 'path/to/files_002.json', etc]`, irrespective of whether a `.meta` file exists).
