### ISSUE TITLE
Small fry for ADM explained article

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#95]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

looking at https://pegasystems.github.io/pega-datascientist-tools/Python/articles/ADMExplained.html and comparing to https://pegasystems.github.io/pega-datascientist-tools/R/articles/adm-explained.html

- auto-hide the not-so-interesting-bits of the code blocks (like the plotting plumbing)
- can we beautify the tables, highlighting the columns/rows of importance
- in the final classifier the resulting bin is hard coded to 6
- the adjusted propensity in the table is wrong, is all the same for all bins

The order of the fields is different but the python version is preferable (sorted)

### Reproducible example

```Python
See python doc
```

### Expected behavior

At par with R version

### Installed versions

<details>

```
Replace this line with the output of pdstools.show_versions(), leave the backticks in place
```

</details>

**Comment by yusufuyanik1** [comment]
[Updated](https://pegasystems.github.io/pega-datascientist-tools/Python/articles/ADMExplained.html) with the points you mentioned. 
- the adjusted propensity in the table is wrong, is all the same for all bins: You can't see this point from the article but it is also fixed. You can check the source actual notebook with code: https://github.com/pegasystems/pega-datascientist-tools/blob/master/examples/articles/ADMExplained.ipynb
- Additional point: Urls are not hidden in the article, will be updated with the next PR

**Comment by operdeck** [comment]
Cool. I can't see it in the article because that only gets republished with
a new version?

Op di 23 mei 2023 om 18:10 schreef yusufuyanik1 ***@***.***>:

**Comment by StijnKas** [comment]
The article should be fully in sync with whatever's there in the repo, it's not tied to any versions. Let's check tomorrow.

**Comment by operdeck** [comment]
R version changed with better formulae and selected a different predictor, one with AUC < the model itself

**Comment by StijnKas** [comment]
@operdeck @yusufuyanik1  just a check - have we fixed this one?

**Comment by yusufuyanik1** [comment]
@StijnKas Yes, we aligned them
