### ISSUE TITLE
Python article Health Check

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#96]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

Lets provide some context first: you can still just run the notebook (name) in your your Python IDE. The app interface provides a way to do some filtering first and does not require the use of a Python dev environment. Maybe the article should be very specific about running the Health Check app.

There is already a “getting started” in the Wiki: https://github.com/pegasystems/pega-datascientist-tools/wiki#getting-started-with-the-python-tools, which has a few more details. Lets make sure we only have one. Perhaps the Wiki is actually the more natural place anyway.

“Downloading the required libraries” gives examples that suggest running this from the terminal system prompt directly. For people using python from e.g. a kernel in VS Code or some other virtual env, lets make sure it is clear it can be done from there too (!pip…).

You say: If your pdstools version is below 3.1. How can people check the pdstools version? (pip show pdstools)

### Reproducible example

```Python
na
```

### Expected behavior

na

### Installed versions

<details>

```
Replace this line with the output of pdstools.show_versions(), leave the backticks in place
```

</details>

**Comment by StijnKas** [comment]
@yusufuyanik1 please have a look. Fyi, 'You say: If your pdstools version is below 3.1. How can people check the pdstools version? (pip show pdstools)' -> I'd prefer `pdstools.show_versions()`

**Comment by yusufuyanik1** [comment]
(pip show pdstools) is already in the article. Right above the Iine "If your pdstools version is below 3.1". 
- if we want them to run `pdstools.show_versions()` in the terminal while they are there, users need to convert the terminal to a python shell, then import pdstools and then they can use show_versions and finally they need to use the exit() command before they are able to run `pdstools run`. Is it worth the extra steps? @StijnKas 
- We intended this to be standalone article which provides quick instructions to start using the app. The version check (over 3.1 and it is actually 3.1.10 now 😅 I will update it in the article) is only valid for app users, and the explanations with screen shots is for very non-technical users whereas in the getting started wiki, it is intended more for people who can code. I understand the duplicate work concern but I think keeping it seperate is not a bad idea. @operdeck yet, still your call 😄. Also we can change the article name to ADM Health Check **App** to make it clear that this article is about the app exclusivly
- In the wiki we download optional app dependencies. Should we do that? @StijnKas 
- I will add this note to the start of downloading required libraries: (You can also run these commands through a python kernel by adding exclamation mark (!). Ex: !pip install --upgrade pdstools[app]) @operdeck

**Comment by StijnKas** [comment]
1. "Is it worth the extra steps? @StijnKas" -> no, good point - this is terminal-only, so let's use pip show I guess ;). 
2. i like having this in the documentation, but it should not replace the getting started guide. The 'general' installation instructions should probably remain in the wiki. Agreed to rename it to app.
3. No strong answer here, we could also say 'if you have any trouble installing dependencies, please refer to (wiki link)'
4. Fine by me

Let's wait with pushing improvements until I release V3.2. Should be within a few days, just need to iron out a few anonymization kinks. That also includes some HC app fixes, so would be nice to only refer to major versions as dependencies.

**Comment by operdeck** [comment]
Why do our own show versions if pip does that for you? Less is more.

Op di 23 mei 2023 om 17:22 schreef Stijn Kas ***@***.***>:

**Comment by StijnKas** [comment]
> Why do our own show versions if pip does that for you? Less is more.

Good reason: because show_versions also shows dependencies, so we can very easily detect if there are any dependency issues rather than just a 'main' pdstools version issue.

I see your point about the sync. Maybe we should have a section on running the qmd separately at the end, and point to it at the top of the page.

**Comment by operdeck** [comment]
Top

Op di 23 mei 2023 om 21:39 schreef Stijn Kas ***@***.***>:
